services:
  - type: web
    name: ssp-auction-backend
    runtime: node
    repo: https://github.com/Electron910/SSP-Auction-Simulator
    rootDirectory: backend
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001